### ISSUE TITLE
有springboot 集成 storm 的例子吗．谢谢

### ISSUE THREAD

**Issue by wurangbo** [itning/BigData#1]

**Comment by itning** [comment]
目前没有 0.0

**Comment by wurangbo** [comment]
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.

我用springboot 打包，提交到集群，运行出现了以上的错误

**Comment by itning** [comment]
> Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 
> 我用springboot 打包，提交到集群，运行出现了以上的错误

打包需要将依赖也打进去

**Comment by wurangbo** [comment]
已经打进去了

**Comment by itning** [comment]
> 已经打进去了

```
<build>
    <plugins>
       <plugin>
          <groupId>org.springframework.boot</groupId>
          	<artifactId>spring-boot-maven-plugin</artifactId>
            	<executions>
                	<execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by wurangbo** [comment]
这种打出来的，本地　java -jar ****.jar没有问题
放到集群模式下执行　storm jar /package/hub-0.0.1-SNAPSHOT.jar com.phoenix.hub.HubApplication  phoenixTopology　会出现以下错误
Error: Could not find or load main class
